{% set name = "brainglobe-napari-io" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/brainglobe-napari-io-{{ version }}.tar.gz
  sha256: 4ee5acf5ecae27f6a7c11fbfe15f7bb39a17940a18a252fb9941c37bcd3687f6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - bg-atlasapi
    - bg-space
    - brainglobe-utils
    - napari
    - python >=3.6
    - tifffile >=2020.8.13
    - numpy
    - pandas

test:
  imports:
    - brainglobe_napari_io
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://brainglobe.info
  summary: Read and write files from the BrainGlobe neuroanatomy suite
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/brainglobe/brainglobe-napari-io

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - adamltyson
