{% set name = "brainglobe-napari-io" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/brainglobe-napari-io-{{ version }}.tar.gz
  sha256: 223c3262da970c586f33647325a495ed7c244ce5117a8ec66d52209102c2c50c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - bg-atlasapi
    - bg-space
    - imlib
    - napari
    - napari-ndtiffs
    - napari-plugin-engine >=0.1.4
    - python >=3.6
    - tifffile >=2020.8.13

test:
  imports:
    - brainglobe_napari_io
    - brainglobe_napari_io.plugins
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://brainglobe.info
  summary: Read and write files from the BrainGlobe neuroanatomy suite
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/brainglobe/brainglobe-napari-io

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - adamltyson
